language: python
sudo: false
python:
  - 2.7
  - 3.6
cache: pip
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - python -m unittest discover -s "test" -p "test*.py"
  - coverage run --source=pymcmcstat -m unittest discover -s "test" -p "test*.py"
notifications:
  email: 
    - prmiles@ncsu.edu
after_success:
  - coveralls
